import { createClient } from "@supabase/supabase-js";

export const supabase = createClient('https://cklczqohgdctyqulkssz.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrbGN6cW9oZ2RjdHlxdWxrc3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzU2ODg4NTUsImV4cCI6MTk5MTI2NDg1NX0.pHrj4nhTLb7WWRrRY4SevQmZX6MfZ7wv5PcXCMNhjlY')